export { default as Title } from './title'
export { default as NavBar } from './navbar'
export { default as SectionContainer } from './sectionContainer'
export { default as Sticky } from './sticky'
export { default as SearchWord } from './searchWord'
export { default as Faq } from './faq'
export { default as Contact } from './contact'
